"use client"
import React, { useState } from 'react';
import ProductCard from './ProductCard';
import Dialog from './Dialog';

const products = [
  { id: 1, title: 'Solar Transformer', image: '/solar.jpg', description: 'A solar transformer is designed to convert the direct current (DC) electricity generated by solar panels into alternating current (AC) electricity, which can be used by homes and businesses or fed into the power grid.' },
  { id: 2, title: 'Power Transformer', image: '/power.jpg', description: 'Power transformers are designed to handle high voltage levels, making them essential in transmitting electricity over long distances with minimal loss. These transformers are widely used in industries, substations, and power plants, playing a key role in maintaining stable and reliable power supply to homes and businesses.' },
  { id: 3, title: 'Dry Type Transformer', image: '/dry.jpg', description: 'Dry-type transformers are electrical transformers that use air as the cooling medium, rather than oil or other liquids.Dry-type transformers are commonly used in indoor applications, such as commercial buildings, industrial facilities, and substations, where space and safety are priorities.' },
  { id: 4, title: 'Distribution Transformer', image: '/dist.jpg', description: 'Distribution transformers are essential components in the electrical grid, responsible for stepping down high voltage from transmission lines to a lower voltage suitable for household and commercial use. Typically installed in residential areas, industrial sites, and on utility poles, these transformers ensure safe and efficient delivery of electricity.' },
  { id: 5, title: 'Furnace Type Transformer', image: '/ftt.jpg', description: 'A furnace-type transformer is specifically designed for use in electric furnaces, which are commonly used in industries like steel, metal processing, and foundries. These transformers are built to handle high currents and provide the necessary voltage to melt metals or maintain the required temperatures in the furnace.' },
  { id: 6, title: 'Compact Stepped Transformer', image: '/compact.jpg', description: 'A compact stepped transformer is a type of transformer designed to step up or step down voltage levels in a more compact and space-efficient form.With a smaller footprint, compact stepped transformers are commonly used in residential, commercial, and industrial settings, where they help manage voltage conversion while minimizing the installation space required.' },
];

const ProductGrid = () => {
  const [selectedProduct, setSelectedProduct] = useState(null);
  const [isDialogOpen, setIsDialogOpen] = useState(false);

  const handleCardClick = (product) => {
    setSelectedProduct(product);
    setIsDialogOpen(true);
  };

  const handleCloseDialog = () => {
    setIsDialogOpen(false);
  };

  return (
    <div className="container mx-auto mt-8 p-4 rounded-lg ">
      <h1 className="text-4xl font-bold text-center mb-8 text-indigo-900">PRODUCTS</h1>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
        {products.map((product) => (
          <ProductCard
            key={product.id}
            product={product}
            onClick={() => handleCardClick(product)}
          />
        ))}
      </div>
      {selectedProduct && (
        <Dialog
          isOpen={isDialogOpen}
          onClose={handleCloseDialog}
          title={selectedProduct.title}
          description={selectedProduct.description}
        />
      )}
    </div>
  );
};

export default ProductGrid;

